// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NZWalks.Api.Data;

#nullable disable

namespace NZWalks.Api.Data.Migrations
{
    [DbContext(typeof(ApiDBContext))]
    partial class ApiDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NZWalks.Api.Data.Entities.RegionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Climate")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Climate = 1,
                            CreatedOn = new DateTime(2024, 10, 7, 15, 7, 12, 611, DateTimeKind.Local).AddTicks(7533),
                            LastUpdatedOn = new DateTime(2024, 10, 7, 15, 7, 12, 611, DateTimeKind.Local).AddTicks(7608),
                            Name = "White Cap Bay"
                        });
                });

            modelBuilder.Entity("NZWalks.Api.Data.Entities.WalkEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Altidude")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("LastUpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<double>("LengthInKm")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PictureUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("Walks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Altidude = 123,
                            CreatedOn = new DateTime(2024, 10, 7, 15, 7, 12, 611, DateTimeKind.Local).AddTicks(7654),
                            Description = "lorem ipsum",
                            LastUpdatedOn = new DateTime(2024, 10, 7, 15, 7, 12, 611, DateTimeKind.Local).AddTicks(7657),
                            LengthInKm = 10.0,
                            Name = "Dummy",
                            PictureUrl = "www.google.be",
                            RegionId = 1,
                            Score = 1
                        },
                        new
                        {
                            Id = 2,
                            Altidude = 6000,
                            CreatedOn = new DateTime(2024, 10, 7, 15, 7, 12, 611, DateTimeKind.Local).AddTicks(7662),
                            Description = "lorem",
                            LastUpdatedOn = new DateTime(2024, 10, 7, 15, 7, 12, 611, DateTimeKind.Local).AddTicks(7664),
                            LengthInKm = 14.0,
                            Name = "Another Dummy",
                            PictureUrl = "www.yahoo.be",
                            RegionId = 1,
                            Score = 2
                        });
                });

            modelBuilder.Entity("NZWalks.Api.Data.Entities.WalkEntity", b =>
                {
                    b.HasOne("NZWalks.Api.Data.Entities.RegionEntity", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
